[package]
name = "authors-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "tls-rustls-ring", "postgres", "time", "uuid" ] }
sqlx-core = "0.8.2"
